[package]
name = "snake-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
crossterm = "0.19.0"
crossterm_screen = "0.1.0"
crossterm_input = "0.2"
